### PR TITLE
fix: crash when user own repo with disabled issue tracker

### PR DESCRIPTION
**Pull request by xgimp**
* replaced if statement with map
* added back the option to run in debug by executing app.py directly

### CODE REVIEW

**Comment by MichalSkoula** [comment]
@xgimp thank you for your PR but

obrazek

**Comment by xgimp** [comment]
now it should work (at least its working on my machine :-)). 

I fixed the issue where the app crashes when some repository does not have issue tracker enabled and some smaller issues along the way

**Comment by MichalSkoula** [comment]
@xgimp thank you again for your commits but I see no issues now

obrazek

**Comment by xgimp** [comment]
Third Time's the Charm! 🤞

**Comment by MichalSkoula** [comment]
Thank you for your commits but now i can see only my "number of issues", not the others

obrazek

**Comment by xgimp** [comment]
it should be fixed 🤞

**Comment by MichalSkoula** [comment]
thanks again for your commits, but now all users' issues are showing in resolved - only mine should show there 

but the bottom stats are corrected, that's true 🍺

obrazek

**Comment by MichalSkoula** [comment]
come on xgimp finish this for the good of the open source community

**Comment by xgimp** [comment]
🤞

**Comment by MichalSkoula** [comment]
It is !!almost!! working, BUT

Now I also see issues without assignee on "New + Open" (at least) - there should be only mine

obrazek

keep up the good work ! #opensource

**Comment by xgimp** [comment]
You want to display here on""New + Open" page only yours issues (issues assigned to user that is logged in) or all issues that are assigned to whoever?

**Comment by MichalSkoula** [comment]
like this https://github.com/MichalSkoula/bitbucket-powertoy/blob/c96ab42f752d0b66f3f40f9c401ed74f6bd121b1/powertoy/app.py#L47

**Comment by MichalSkoula** [comment]
+1

**Comment by MichalSkoula** [comment]
While you're at it, I'd like to see "On Hold" issues from everyone, as well as Resolved

**Comment by MichalSkoula** [comment]
i will merge it and fix it later

**Comment by MichalSkoula** [comment]
i have fixed it here https://github.com/MichalSkoula/bitbucket-powertoy/commit/162c2100b9ac1d7ec5fdc1b7943dde5acaf2e1f0

and added new checkbox for you

obrazek

**Comment by xgimp** [comment]
@MichalSkoula Very lovely. I think the whole community will appreciate this!

**Comment by MichalSkoula** [comment]
Not only our small community, but whole society and humanity can benefit from these commits

**Pull request merged**
